In [1]:
import pandas as pd
import numpy as np

In [5]:
data=pd.DataFrame({
    'x0':[1,2,3,4,5],
    'x1':[0.01,-0.01,0.25,-4.1,0],
    'y':[-1.5,0,3.6,1.3,-2]})

In [6]:
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [7]:
data.columns

Index(['x0', 'x1', 'y'], dtype='object')

In [8]:
data.values

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

In [9]:
df2=pd.DataFrame(data.values,columns=['one','two','three'])

In [10]:
df2

one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

In [11]:
df3=data.copy()

In [12]:
df3

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [13]:
df3['strings']=['a','b','c','d','e']

In [14]:
df3

x0    x1    y strings
0   1  0.01 -1.5       a
1   2 -0.01  0.0       b
2   3  0.25  3.6       c
3   4 -4.10  1.3       d
4   5  0.00 -2.0       e

In [15]:
df3.values

array([[1, 0.01, -1.5, 'a'],
       [2, -0.01, 0.0, 'b'],
       [3, 0.25, 3.6, 'c'],
       [4, -4.1, 1.3, 'd'],
       [5, 0.0, -2.0, 'e']], dtype=object)

In [16]:
model_cols=['x0','x1']

In [18]:
model_cols

['x0', 'x1']

In [19]:
data.loc[:,model_cols].values

array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

In [20]:
np.ones((10,5)).shape

(10, 5)

In [27]:
np.ones((3,4,5),dtype=np.float64).strides

(160, 40, 8)

In [23]:
ints=np.ones(10,dtype=np.uint16)

In [24]:
ints

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint16)

In [25]:
floats=np.ones(10,dtype=np.float)

In [26]:
floats

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
arr=np.arange(8)

In [29]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [30]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [31]:
arr.reshape((4,2)).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [37]:
arr=np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
arr.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [39]:
a=np.ones((3,5))

In [40]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
a.shape

(3, 5)

In [43]:
arr.reshape(a.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
arr=np.arange(15).reshape((5,3))

In [45]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [46]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
###Concatination and Splitting Arrays

In [49]:
arr1=np.array([[1,2,3],[4,5,6]])

In [50]:
arr2=np.array([[7,8,9],[10,11,12]])

In [51]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [52]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [53]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [54]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [56]:
arr=np.random.randn(5,2)

In [57]:
arr

array([[ 0.47267049, -0.14313353],
       [ 2.0993755 ,  0.83304212],
       [ 1.08802145,  1.1901412 ],
       [-0.01054822,  1.81608934],
       [ 0.01823765,  0.75831154]])

In [58]:
first,second,third=np.split(arr,[1,3])

In [59]:
first

array([[ 0.47267049, -0.14313353]])

In [60]:
second

array([[2.0993755 , 0.83304212],
       [1.08802145, 1.1901412 ]])

In [61]:
third

array([[-0.01054822,  1.81608934],
       [ 0.01823765,  0.75831154]])

In [1]:
##Repeating Element :

In [3]:
import numpy as np
arr=np.arange(3)

In [4]:
arr

array([0, 1, 2])

In [5]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [6]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [8]:
arr=np.random.randn(2,2)

In [9]:
arr

array([[ 0.66409053,  0.23949739],
       [-1.36684024,  1.02938341]])

In [10]:
arr.repeat(2,axis=0)

array([[ 0.66409053,  0.23949739],
       [ 0.66409053,  0.23949739],
       [-1.36684024,  1.02938341],
       [-1.36684024,  1.02938341]])

In [11]:
arr.repeat([2,3],axis=0)

array([[ 0.66409053,  0.23949739],
       [ 0.66409053,  0.23949739],
       [-1.36684024,  1.02938341],
       [-1.36684024,  1.02938341],
       [-1.36684024,  1.02938341]])

In [12]:
arr.repeat([2,3],axis=1)

array([[ 0.66409053,  0.66409053,  0.23949739,  0.23949739,  0.23949739],
       [-1.36684024, -1.36684024,  1.02938341,  1.02938341,  1.02938341]])

In [13]:
arr

array([[ 0.66409053,  0.23949739],
       [-1.36684024,  1.02938341]])

In [14]:
np.tile(arr,(2,1))

array([[ 0.66409053,  0.23949739],
       [-1.36684024,  1.02938341],
       [ 0.66409053,  0.23949739],
       [-1.36684024,  1.02938341]])

In [15]:
##Broadcasting

In [16]:
arr=np.arange(5)

In [17]:
arr

array([0, 1, 2, 3, 4])

In [18]:
arr*4

array([ 0,  4,  8, 12, 16])

In [19]:
arr=np.random.randn(4,3)

In [20]:
arr

array([[-0.60183791, -0.21024079,  0.32857385],
       [ 1.76204582,  0.4171603 ,  2.34650044],
       [ 1.1199207 ,  2.77215293, -0.96923199],
       [-0.90669718, -0.3660389 ,  0.06775291]])

In [22]:
arr.mean(0)

array([0.34335786, 0.65325838, 0.4433988 ])

In [23]:
demeaned=arr-arr.mean(0)

In [24]:
demeaned

array([[-0.94519577, -0.86349918, -0.11482495],
       [ 1.41868797, -0.23609808,  1.90310164],
       [ 0.77656284,  2.11889455, -1.4126308 ],
       [-1.25005504, -1.01929729, -0.37564589]])

In [25]:
demeaned.mean(0)

array([0.00000000e+00, 0.00000000e+00, 1.38777878e-17])

In [26]:
arr

array([[-0.60183791, -0.21024079,  0.32857385],
       [ 1.76204582,  0.4171603 ,  2.34650044],
       [ 1.1199207 ,  2.77215293, -0.96923199],
       [-0.90669718, -0.3660389 ,  0.06775291]])

In [27]:
row_means=arr.mean(1)

In [28]:
row_means

array([-0.16116829,  1.50856886,  0.97428055, -0.40166106])

In [31]:
row_means.shape

(4,)

In [32]:
row_means.reshape((4,1))

array([[-0.16116829],
       [ 1.50856886],
       [ 0.97428055],
       [-0.40166106]])

In [33]:
demeaned=arr-row_means.reshape((4,1))

In [34]:
demeaned

array([[-0.44066963, -0.04907251,  0.48974214],
       [ 0.25347696, -1.09140855,  0.83793159],
       [ 0.14564015,  1.79787239, -1.94351254],
       [-0.50503612,  0.03562216,  0.46941397]])

In [35]:
demeaned.mean(1)

array([ 3.70074342e-17,  0.00000000e+00, -1.48029737e-16,  0.00000000e+00])

In [36]:
##Sorting

In [37]:
arr=np.random.randn(6)

In [38]:
arr

array([-1.45373385,  1.24203373,  0.82357489, -0.44911546,  0.7799908 ,
       -0.94454489])

In [39]:
arr.sort()

In [40]:
arr

array([-1.45373385, -0.94454489, -0.44911546,  0.7799908 ,  0.82357489,
        1.24203373])

In [41]:
arr=np.random.randn(3,5)

In [42]:
arr

array([[-1.6375692 ,  0.302912  , -1.56994609,  0.11163676,  0.57999617],
       [-0.80763175, -1.93771919, -0.87654701,  0.2986107 , -0.62214636],
       [-0.95256457,  0.86585072, -0.28833728, -0.98359764, -0.89684565]])

In [43]:
arr[:,0].sort()

In [44]:
arr

array([[-1.6375692 ,  0.302912  , -1.56994609,  0.11163676,  0.57999617],
       [-0.95256457, -1.93771919, -0.87654701,  0.2986107 , -0.62214636],
       [-0.80763175,  0.86585072, -0.28833728, -0.98359764, -0.89684565]])

In [45]:
arr=np.random.randn(5)

In [46]:
arr

array([ 0.66863054, -1.60763481,  0.34879864, -0.19937611, -0.64508523])

In [47]:
np.sort(arr)

array([-1.60763481, -0.64508523, -0.19937611,  0.34879864,  0.66863054])

In [48]:
arr

array([ 0.66863054, -1.60763481,  0.34879864, -0.19937611, -0.64508523])

In [49]:
arr=np.random.randn(3,5)

In [50]:
arr

array([[ 1.19815289, -1.99369913,  0.12026551, -0.01989851,  0.42224178],
       [ 0.2288821 ,  0.91341034, -0.48697335, -0.43329149,  0.802804  ],
       [ 1.05690023, -0.11847522, -2.27565798,  0.24232227, -0.26513635]])

In [52]:
arr.sort(axis=1)

In [53]:
arr

array([[-1.99369913, -0.01989851,  0.12026551,  0.42224178,  1.19815289],
       [-0.48697335, -0.43329149,  0.2288821 ,  0.802804  ,  0.91341034],
       [-2.27565798, -0.26513635, -0.11847522,  0.24232227,  1.05690023]])

In [54]:
arr[:,::-1]

array([[ 1.19815289,  0.42224178,  0.12026551, -0.01989851, -1.99369913],
       [ 0.91341034,  0.802804  ,  0.2288821 , -0.43329149, -0.48697335],
       [ 1.05690023,  0.24232227, -0.11847522, -0.26513635, -2.27565798]])

In [55]:
##Indirect sorts

In [56]:
values=np.array([5,0,1,3,2])

In [59]:
indexer=values.argsort()

In [60]:
values[indexer]

array([0, 1, 2, 3, 5])

In [61]:
arr=np.random.randn(3,5)

In [62]:
arr=np.random.randn(3,5)

In [63]:
arr[0]=values

In [64]:
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [-0.50086604,  0.17750656, -0.53846207, -1.01625899,  0.80709561],
       [-1.75055667,  0.23827445, -0.32795419, -0.00898011,  0.87718559]])