In [1]:
# Concatenation along the Axis

In [2]:
arr=np.arange(12).reshape((3,4))

<IPython.core.display.Javascript object>

In [3]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
np.concatenate([arr,arr],axis=1)

<IPython.core.display.Javascript object>

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [5]:
s1=pd.Series([0,1],index=['a','b'])

<IPython.core.display.Javascript object>

In [6]:
s2=pd.Series([2,3,4],index=['c','d','e'])

<IPython.core.display.Javascript object>

In [7]:
s3=pd.Series([5,6],index=['f','g'])

<IPython.core.display.Javascript object>

In [8]:
s1

a    0
b    1
dtype: int64

In [9]:
s2

c    2
d    3
e    4
dtype: int64

In [10]:
s3

f    5
g    6
dtype: int64

In [11]:
pd.concat([s1,s2,s3])

<IPython.core.display.Javascript object>

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [12]:
pd.concat([s1,s2,s3],axis=1)

<IPython.core.display.Javascript object>

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [13]:
s4=pd.concat([s1,s3])

<IPython.core.display.Javascript object>

In [14]:
s4

a    0
b    1
f    5
g    6
dtype: int64

In [15]:
pd.concat([s1,s4],axis=1)

<IPython.core.display.Javascript object>

0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [17]:
pd.concat([s1,s4],axis=1,join='inner')

<IPython.core.display.Javascript object>

0  1
a  0  0
b  1  1

In [18]:
result=pd.concat([s1,s1,s3],keys=['one','two','three'])

<IPython.core.display.Javascript object>

In [19]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [20]:
pd.concat([s1,s2,s3],axis=1,keys=['one','two','three'])

<IPython.core.display.Javascript object>

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [21]:
df1=pd.DataFrame(np.arange(6).reshape(3,2),index=['a','b','c'],columns=['one','two'])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [22]:
df2=pd.DataFrame(5+np.arange(4).reshape(2,2),index=['a','c'],columns=['three','four'])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [23]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [24]:
df2

three  four
a      5     6
c      7     8

In [25]:
pd.concat([df1,df2],axis=1,keys=['level1','level2'])

<IPython.core.display.Javascript object>

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [26]:
pd.concat({'level1':df1,'level2':df2},axis=1)

<IPython.core.display.Javascript object>

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [28]:
## Combining Data with overlap

In [29]:
import numpy as np
a=pd.Series([np.nan,2.5,np.nan,3.5,4.5,np.nan],index=['f','e','d','c','b','a'])

<IPython.core.display.Javascript object>

In [32]:
b=pd.Series(np.arange(len(a),dtype=np.float64),index=['f','e','d','c','b','a'])

<IPython.core.display.Javascript object>

In [33]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [34]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64

In [35]:
b[-1]=np.nan

In [36]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [37]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [38]:
np.where(pd.isnull(a),b,a)

<IPython.core.display.Javascript object>

array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [39]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [41]:
df1=pd.DataFrame({'a':[1,np.nan,5,np.nan],'b':[np.nan,2,np.nan,6],'c':range(2,18,4)})

<IPython.core.display.Javascript object>

In [44]:
df2=pd.DataFrame({'a':[5,4,np.nan,3,7],'b':[np.nan,3,4,6,8]})

<IPython.core.display.Javascript object>

In [45]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [46]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [47]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN