In [1]:
import numpy as np

In [3]:
a=np.array([1,2,'Rohith'])

In [4]:
a

array(['1', '2', 'Rohith'], dtype='<U11')

In [5]:
type(a)

numpy.ndarray

In [6]:
#Upcasting:

In [7]:
np.array([1,2,3.0])

array([1., 2., 3.])

In [8]:
# two dimension
a=([1,2,3],[4,5,6])

In [9]:
np.array(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b=[3,4,5]

In [12]:
np.array(b,ndmin=5)

array([[[[[3, 4, 5]]]]])

In [13]:
#dtype

In [15]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [16]:
#Creating an array from sub-classes:

In [17]:
a=([1,2,3],[3,4,5])

In [19]:
b=np.array(a)

In [20]:
b

array([[1, 2, 3],
       [3, 4, 5]])

In [22]:
np.mat(b)

matrix([[1, 2, 3],
        [3, 4, 5]])

In [25]:
np.mat([1,2,3])

matrix([[1, 2, 3]])

# numpy.asarray

In [26]:
a=[1,2]#Convert a list into an array:

In [27]:
type(a)

list

In [28]:
np.asarray(a)#Convert a list into an array:

array([1, 2])

In [29]:
type(np.asarray(a))

numpy.ndarray

In [30]:
b=[2,3]

In [31]:
np.array(b)#Existing arrays are not copied

array([2, 3])

In [32]:
type(np.array(b))

numpy.ndarray

In [33]:
a=np.array([1,2],dtype= float)

In [34]:
a

array([1., 2.])

In [35]:
# ndarray subclasses are not passed through

In [36]:
issubclass(np.matrix,np.ndarray)

True

In [37]:
a=np.array([1,2])

In [38]:
a

array([1, 2])

In [39]:
np.asarray(a) is a

True

In [40]:
np.asarray([1,2]) is a

False

In [41]:
np.asarray([1,2])

array([1, 2])

In [42]:
np.asarray([1,2,3])

array([1, 2, 3])

In [43]:
type(np.asarray(a))

numpy.ndarray

In [44]:
type(np.array(a))

numpy.ndarray

# numpy.asanyarray

In [50]:
a=[1,2]

In [51]:
np.asanyarray(a)

array([1, 2])

In [47]:
a=np.matrix([1,2])

In [48]:
a

matrix([[1, 2]])

In [52]:
np.asanyarray([1,2]) is a

False

In [53]:
np.array(a, copy=True)  

array([1, 2])

In [54]:
#Create an array x, with a reference y and a copy z:

In [58]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [59]:
y = x

In [60]:
z=np.copy(x)

In [61]:
z

array([1, 2, 3])

In [63]:
y[0]=100

In [64]:
y

array([100,   2,   3])

In [65]:
x

array([100,   2,   3])

In [67]:
id(x[0])

476824021872

In [68]:
id(x) 

476824082272

In [69]:
id(y)

476824082272

In [70]:
#Construct an array by executing a function over each coordinate.

# numpy.fromfunction

In [72]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [74]:
np.fromfunction(lambda i,j : i * j,(3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [75]:
#Create a new 1-dimensional array from an iterable object.

In [76]:
a=[x*x for x in range(0,5)]

In [77]:
a

[0, 1, 4, 9, 16]

In [78]:
np.fromiter(a,float)

array([ 0.,  1.,  4.,  9., 16.])

In [79]:
#A new 1-D array initialized from text data in a string

In [80]:
a = np.fromstring('234 234',sep=' ')
a

array([234., 234.])

In [81]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

In [82]:
# How to create create a record array from a (flat) list of arrays

In [83]:
x1=np.array([1,2,3])

In [84]:
x2=np.array([1,2,"Rohith"])

In [85]:
x2

array(['1', '2', 'Rohith'], dtype='<U11')

In [86]:
type(x2)

numpy.ndarray

In [87]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

# data types

In [89]:
a=[1,2,3]

In [90]:
np.array(a)

array([1, 2, 3])

In [92]:
print("Type/class of array:",type(a))
print("Here is the vector:",a)

Type/class of array: <class 'list'>
Here is the vector: [1, 2, 3]


In [93]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)

In [94]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
mat.ndim  #Dimension of this matrix

2

In [96]:
mat.size #Size of this matrix

9

In [97]:
mat.shape #Shape of this matrix:

(3, 3)

In [98]:
mat.dtype # Data type of this matrix

dtype('int32')

In [99]:
b=np.array([(1,2,3),(4,5,6)]) ##Matrix made from tuples, not lists\

In [100]:
b

array([[1, 2, 3],
       [4, 5, 6]])

# arange and linspace

In [101]:
np.array([2,6.5])

array([2. , 6.5])

In [102]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [103]:
list(range(50,-1,5))

[]

In [104]:
np.arange(0,11,2.5)# Numbers spaced apart by 2.5

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [105]:
np.arange(5.0,-1,-5)#Every 5th number from 50 in reverse order

array([5., 0.])

In [109]:
np.linspace(4,10,50)

array([ 4.        ,  4.12244898,  4.24489796,  4.36734694,  4.48979592,
        4.6122449 ,  4.73469388,  4.85714286,  4.97959184,  5.10204082,
        5.2244898 ,  5.34693878,  5.46938776,  5.59183673,  5.71428571,
        5.83673469,  5.95918367,  6.08163265,  6.20408163,  6.32653061,
        6.44897959,  6.57142857,  6.69387755,  6.81632653,  6.93877551,
        7.06122449,  7.18367347,  7.30612245,  7.42857143,  7.55102041,
        7.67346939,  7.79591837,  7.91836735,  8.04081633,  8.16326531,
        8.28571429,  8.40816327,  8.53061224,  8.65306122,  8.7755102 ,
        8.89795918,  9.02040816,  9.14285714,  9.26530612,  9.3877551 ,
        9.51020408,  9.63265306,  9.75510204,  9.87755102, 10.        ])

# Matrix creation

In [111]:
np.zeros(4)  #Vector of zeroes

array([0., 0., 0., 0.])

In [113]:
np.zeros((3,4))# Matrix of zeroes 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [114]:
np.ones(4)

array([1., 1., 1., 1.])

In [116]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [117]:
np.ones((5,2,8))# Note matrix dimension specified by Tuples

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [118]:
5+np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [119]:
np.empty((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [120]:
np.eye(4) #Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [123]:
np.eye(10,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [124]:
np.arange(3)

array([0, 1, 2])

In [125]:
np.arange(3.0)

array([0., 1., 2.])

In [128]:
np.arange(3,7,2)

array([3, 5])

In [129]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [130]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [131]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [132]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [137]:
np.logspace(2.0,3.0, 4 , base=10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [138]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [139]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [140]:
#Extract a diagonal or construct a diagonal array.

In [141]:
x = np.arange(16).reshape((-1,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [142]:
np.diag(x)

array([ 0,  5, 10, 15])

In [143]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [144]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [145]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [146]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [147]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [148]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [149]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [150]:
#return a Lower triangle of an array.

In [151]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [152]:
#return Upper triangle of an array.

In [153]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

In [154]:
np.random.rand(2,3) # Random number generation (from Uniform distribution)

array([[0.27164526, 0.21505814, 0.20736626],
       [0.29519488, 0.94790726, 0.81071572]])

In [155]:
np.random.randn(4,3)

array([[-0.74828037,  0.22433026,  1.65319295],
       [-0.01481611,  1.12748684, -0.52834341],
       [-0.28818368,  0.37748107,  1.40128561],
       [-0.69697296,  0.67478357,  0.35681938]])

In [156]:
np.random.randint(1,100,(4,4))

array([[ 2, 64, 43, 92],
       [48, 83, 23, 63],
       [88, 40, 81, 18],
       [85, 41, 66, 42]])

In [159]:
arr=np.arange(0,11)

In [161]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [162]:
 arr[7]

7

In [163]:
arr[3:6:2] #Elements from 3rd to 5th index are

array([3, 5])

In [164]:
arr[3:6]

array([3, 4, 5])

In [166]:
arr[:4] #Elements up to 4th index are:

array([0, 1, 2, 3])