# Numpy 

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.It has bindings of C and C++ arrays

### What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5]

In [3]:
array=np.array(my_lst)

In [4]:
array

array([1, 2, 3, 4, 5])

In [5]:
type(array)

numpy.ndarray

In [6]:
#Multinested array

In [7]:
a=[1,2,3,4,5]
b=[2,2,3,5,6]
d=[9,2,4,6,3]

In [10]:
arr=np.array([a,b,d])

In [11]:
arr

array([[1, 2, 3, 4, 5],
       [2, 2, 3, 5, 6],
       [9, 2, 4, 6, 3]])

In [12]:
type(arr)

numpy.ndarray

In [13]:
arr.shape#To check the shape of the array

(3, 5)

In [14]:
# Indexing
array_1=np.array([1,2,3,4,5,6])

In [15]:
array_1

array([1, 2, 3, 4, 5, 6])

In [17]:
array_1[2]

3

In [18]:
arr

array([[1, 2, 3, 4, 5],
       [2, 2, 3, 5, 6],
       [9, 2, 4, 6, 3]])

In [19]:
arr[1:,:2]

array([[2, 2],
       [9, 2]])

In [20]:
arr[:,3:]

array([[4, 5],
       [5, 6],
       [6, 3]])

In [21]:
arr=np.array([1,2,3,4,5])

In [22]:
arr[3:]=100

In [23]:
arr

array([  1,   2,   3, 100, 100])

In [24]:
#Some useful conditions in EDA


In [25]:
val=3
arr[arr<3]

array([1, 2])

In [26]:
#Create array and reshape
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [28]:
arr1=np.arange(0,10).reshape(2,5)

In [29]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
arr2=np.arange(0,10).reshape(2,5)

In [31]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [35]:
np.ones([2,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
#Random Distribution

In [37]:
np.random.rand(3,3)

array([[0.57143445, 0.46195146, 0.79270991],
       [0.051899  , 0.98775363, 0.28679431],
       [0.48361078, 0.82912278, 0.52057731]])

In [38]:
a=np.random.randn(4,4)

In [39]:
a

array([[ 0.10455434,  0.88772223,  0.45378334,  0.68305766],
       [-1.56197895,  0.39123097, -1.92963727, -0.52036216],
       [-0.58265386,  1.27190869, -1.87144388, -0.42664252],
       [ 1.49612624, -0.58578873,  1.25600628, -1.15760778]])

In [45]:
np.random.randint(0,100,8)

array([38, 62, 32, 34, 69, 32, 58, 43])

In [46]:
np.random.randint(0,100,8).reshape(4,2)

array([[88, 89],
       [95, 74],
       [15, 24],
       [25, 59]])