In [1]:
import pandas as pd

In [2]:
from pandas import Series ,DataFrame

## Series 

- Series is a one dimensional array - like object containing a sequence of values(of similar types to Numpy types) and an associated array of data labels is called Index

In [3]:
obj = pd.Series([4,5,6,7])

In [4]:
obj

0    4
1    5
2    6
3    7
dtype: int64

In [5]:
obj.values

array([4, 5, 6, 7], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2=pd.Series([1,2,3,4],index=['a','b','c','d'])

In [8]:
obj2

a    1
b    2
c    3
d    4
dtype: int64

In [9]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [10]:
obj2['a']

1

In [11]:
obj2['c']

3

In [13]:
obj2[['a','c','d']]

a    1
c    3
d    4
dtype: int64

In [14]:
obj2[obj2>2]

c    3
d    4
dtype: int64

In [15]:
obj2*2

a    2
b    4
c    6
d    8
dtype: int64

In [16]:
np.exp(obj2)

<IPython.core.display.Javascript object>

a     2.718282
b     7.389056
c    20.085537
d    54.598150
dtype: float64

In [17]:
'b' in obj2

True

In [18]:
'e' in obj2

False

In [31]:
sdata={'ohio':3500,'Texas':5252,'Oregon':1600,'utah':5000}

In [32]:
obj3=pd.Series(sdata)

In [33]:
obj3

ohio      3500
Texas     5252
Oregon    1600
utah      5000
dtype: int64

In [34]:
states=['California','ohio','Oregon','Texas']

In [35]:
obj4=pd.Series(sdata,index=states)

In [36]:
obj4

California       NaN
ohio          3500.0
Oregon        1600.0
Texas         5252.0
dtype: float64

In [37]:
pd.isnull(obj4)

California     True
ohio          False
Oregon        False
Texas         False
dtype: bool

In [38]:
pd.notnull(obj4)

California    False
ohio           True
Oregon         True
Texas          True
dtype: bool

In [39]:
obj4.isnull()

California     True
ohio          False
Oregon        False
Texas         False
dtype: bool

In [40]:
obj3

ohio      3500
Texas     5252
Oregon    1600
utah      5000
dtype: int64

In [41]:
obj3+obj4

California        NaN
Oregon         3200.0
Texas         10504.0
ohio           7000.0
utah              NaN
dtype: float64

In [42]:
obj4.name='population'

In [43]:
obj4.index.name='state'

In [44]:
obj4

state
California       NaN
ohio          3500.0
Oregon        1600.0
Texas         5252.0
Name: population, dtype: float64

In [45]:
obj

0    4
1    5
2    6
3    7
dtype: int64

In [46]:
obj.index=['Bob','Steve','Jeff','Ryan']

In [47]:
obj

Bob      4
Steve    5
Jeff     6
Ryan     7
dtype: int64

## DataFrame 

- A data frame represents a rectangular table of data and contains an ordered collection of columns , each of which can be a different value type
- The data frame has both column and row indexes

In [1]:
data={'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
      'year':[2000,2001,2002,2001,2002,2003],
      'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}

In [2]:
frame=pd.DataFrame(data)

<IPython.core.display.Javascript object>

In [3]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [4]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [5]:
pd.DataFrame(data,columns=['year','state','pop']) # To rearrange the columns

<IPython.core.display.Javascript object>

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [6]:
frame2=pd.DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five','six'])

<IPython.core.display.Javascript object>

In [7]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [8]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [9]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [10]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [11]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [13]:
frame2['debt']=16.5

In [14]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [16]:
frame2['debt']=np.arange(6.0)

<IPython.core.display.Javascript object>

In [17]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [18]:
val=pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])

<IPython.core.display.Javascript object>

In [19]:
frame2['debt']=val

In [20]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [23]:
frame2['eastern']=frame2.state=='Ohio'

In [25]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [26]:
del frame2['eastern']

In [28]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [30]:
pop={'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [31]:
frame3=pd.DataFrame(pop)

<IPython.core.display.Javascript object>

In [32]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [33]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [34]:
pd.DataFrame(pop,index=[2001,2002,2003])

<IPython.core.display.Javascript object>

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [35]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [36]:
frame3.index.name='year'

In [37]:
frame3

Nevada  Ohio
year              
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [38]:
frame3.index.name='year';frame3.columns.name='state'

In [39]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [40]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [41]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## Index Objects

- Pandas Index objects are responsible for holding the axis labels and other metadata

In [45]:
obj=pd.Series(range(3),index=['a','b','c'])

<IPython.core.display.Javascript object>

In [46]:
obj

a    0
b    1
c    2
dtype: int64

In [47]:
index=obj.index

In [48]:
index

Index(['a', 'b', 'c'], dtype='object')

In [49]:
index[1:]

Index(['b', 'c'], dtype='object')

In [50]:
index[1]

'b'

In [51]:
labels=pd.Index(np.arange(3))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [52]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [54]:
obj2=pd.Series([1.5,-2.5,0],index=labels)

<IPython.core.display.Javascript object>

In [55]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [56]:
obj2.index is labels

True

In [57]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [58]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [59]:
'Ohio' in frame3.columns

True

In [60]:
2003 in frame.columns

False

In [61]:
dup_labels=pd.Index(['foo','foo','bar','bar'])

<IPython.core.display.Javascript object>

In [62]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## Reindexing

- It is an important method on pandas objects is reindex,which means to create a new object with the data confirmed on a new index 

In [63]:
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])

<IPython.core.display.Javascript object>

In [64]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [65]:
obj2=obj.reindex(['a','b','c','d','e'])

In [66]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [67]:
obj3=pd.Series(['blue','purple','yellow'],index=[0,2,4])

<IPython.core.display.Javascript object>

In [68]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [69]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [77]:
frame=pd.DataFrame(np.arange(9).reshape((3,3)),
                index=['a','b','c'],
                columns=['Ohio','Texas','California'])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [78]:
frame

Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8

In [79]:
frame2=frame.reindex(['a','b','c','d'])

In [80]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   6.0    7.0         8.0
d   NaN    NaN         NaN

In [81]:
states=['Texas','Utah','California']

In [82]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
c      7   NaN           8

## Dropping entries from an Axis

In [1]:
obj=pd.Series(np.arange(5),index=['a','b','c','d','e'])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [2]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [3]:
new_obj=obj.drop('c')

In [4]:
new_obj

a    0
b    1
d    3
e    4
dtype: int32

In [5]:
obj.drop(['d','c'])

a    0
b    1
e    4
dtype: int32

In [6]:
data=pd.DataFrame(np.arange(16).reshape(4,4),
                 index=['Ohio','Colorado','Utah','New York'],
                 columns=['one','two','three','four'])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [7]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [8]:
data.drop(['Ohio','Colorado'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [9]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [10]:
data.drop(['two'],axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [12]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [13]:
obj.drop('c',inplace=True)

In [14]:
obj

a    0
b    1
d    3
e    4
dtype: int32

## Indexing ,Slection,Filtering

In [15]:
obj=pd.Series(np.arange(4),index=['a','b','c','d'])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [16]:
obj

a    0
b    1
c    2
d    3
dtype: int32

In [17]:
obj['b']

1

In [18]:
obj[1]

1

In [19]:
obj[2:4]

c    2
d    3
dtype: int32

In [20]:
obj[['b','a','d']]

b    1
a    0
d    3
dtype: int32

In [21]:
obj[[1,3]]

b    1
d    3
dtype: int32

In [22]:
obj[obj<2]

a    0
b    1
dtype: int32

In [23]:
obj['b':'c']

b    1
c    2
dtype: int32

In [24]:
obj['b':'c']=5

In [25]:
obj

a    0
b    5
c    5
d    3
dtype: int32

In [26]:
data=pd.DataFrame(np.arange(16).reshape(4,4),
                 index=['Ohio','Colorado','Utah','NewYork'],
                 columns=['one','two','three','four'])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [27]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [28]:
data['two']

Ohio         1
Colorado     5
Utah         9
NewYork     13
Name: two, dtype: int32

In [29]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
NewYork      14   12

In [30]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [31]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [32]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
NewYork   False  False  False  False

In [33]:
data[data<5]=0

In [34]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15