## Integer Indexes

In [1]:
ser =pd.Series(np.arange(3))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [2]:
ser

0    0
1    1
2    2
dtype: int32

In [3]:
ser2=pd.Series(np.arange(3),index=['a','b','c'])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [4]:
ser2

a    0
b    1
c    2
dtype: int32

In [5]:
ser[:1]

0    0
dtype: int32

In [6]:
ser.loc[:1]

0    0
1    1
dtype: int32

## Arithmatic and Data Alignment

In [7]:
s1=pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])

<IPython.core.display.Javascript object>

In [8]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [9]:
s2=pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

<IPython.core.display.Javascript object>

In [10]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [11]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [12]:
df1=pd.DataFrame(np.arange(9).reshape((3,3)),columns=list('bcd'),index=['Ohio','Texas','Colorado'])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [13]:
df2=pd.DataFrame(np.arange(12).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [14]:
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [15]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [16]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [17]:
df1=pd.DataFrame({'A':[1,2]})

<IPython.core.display.Javascript object>

In [18]:
df2=pd.DataFrame({'B':[3,4]})

<IPython.core.display.Javascript object>

In [19]:
df1

A
0  1
1  2

In [20]:
df2

B
0  3
1  4

In [21]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

## Arithmatic methods with fill values

In [25]:
df1=pd.DataFrame(np.arange(12).reshape((3,4)),columns=list('abcd'))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [26]:
df2=pd.DataFrame(np.arange(20).reshape((4,5)),columns=list('abcde'))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [27]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [28]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [29]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [30]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [31]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [32]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [33]:
df1.reindex(columns=df2.columns,fill_value=0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

### Operations between Data Frame and Series

In [34]:
arr=np.arange(12).reshape((3,4))

<IPython.core.display.Javascript object>

In [35]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
arr[0]

array([0, 1, 2, 3])

In [37]:
arr-arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [38]:
frame=pd.DataFrame(np.arange(12).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [39]:
series=pd.Series(range(3),index=['b','e','f'])

<IPython.core.display.Javascript object>

In [40]:
frame+series

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [41]:
series1=frame['d']

In [42]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [44]:
series1

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int32

### Sorting and Ranking 

In [45]:
frame=pd.DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [46]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [47]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [48]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [49]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [50]:
obj=pd.Series([4,7,-3,-2])

<IPython.core.display.Javascript object>

In [51]:
obj.sort_values()

2   -3
3   -2
0    4
1    7
dtype: int64

In [52]:
obj=pd.Series([4,np.nan,7,np.nan,-3,2])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [53]:
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [54]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [55]:
frame=pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

<IPython.core.display.Javascript object>

In [56]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [57]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [59]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

### Axis Indexes with Duplicate Labels 

In [60]:
obj=pd.Series(range(5),index=['a','a','b','b','c'])

<IPython.core.display.Javascript object>

In [61]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [62]:
obj.index.is_unique

False

In [63]:
obj['a']

a    0
a    1
dtype: int64

In [66]:
obj['c']

4

In [67]:
df=pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b'])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [68]:
df

0         1         2
a  0.306213  1.337970 -0.930368
a  0.201392  1.232500 -0.564307
b -0.639115 -0.523490 -0.995301
b  0.889168 -1.598548  1.442227

In [69]:
df.loc['b']

0         1         2
b -0.639115 -0.523490 -0.995301
b  0.889168 -1.598548  1.442227

### Summarizing and Computing Descriptive Statistics 

In [70]:
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=['a','b','c','d'],columns=['one','two'])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [71]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [72]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [73]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [74]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [77]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [78]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

## Unique values ,Value Counts and Membership

In [86]:
obj=pd.Series(['c','a','d','a','a','b','b','c','c'])

<IPython.core.display.Javascript object>

In [87]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [88]:
uniques=obj.unique()

In [89]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [90]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [91]:
pd.value_counts(obj.values,sort=False)

<IPython.core.display.Javascript object>

c    3
b    2
d    1
a    3
dtype: int64

In [92]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [93]:
mask=obj.isin(['b','c'])

In [94]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [95]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [96]:
data=pd.DataFrame({'Qu1':[1,3,4,3,4],'Qu2':[2,3,1,2,3],'Qu3':[1,5,2,4,4]})

<IPython.core.display.Javascript object>

In [97]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [99]:
result=data.apply(pd.value_counts).fillna(0)

<IPython.core.display.Javascript object>

In [100]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0