In [1]:
 # Basics of Python

In [2]:
1+1

2

In [3]:
4*5

20

In [4]:
2/10

0.2

In [5]:
10/2

5.0

In [6]:
10%2

0

In [7]:
10**2

100

In [8]:
## How to check the data type

In [9]:
type(True)

bool

In [10]:
type("Hello")

str

In [11]:
##Strings

In [12]:
"Hello"

'Hello'

In [13]:
'Rohith Neelagiriyappa'

'Rohith Neelagiriyappa'

In [14]:
type('Rohith Neelagiriyappa')

str

In [15]:
## Variable Assignment

In [17]:
# syntax
#var_name=values

In [18]:
a=10

In [19]:
type(a)

int

In [20]:
a='London'

In [21]:
type(a)

str

In [22]:
## Mathematical operation with Variable Assigment

In [23]:
a=10
b=20

In [24]:
print(a*b)

200


In [25]:
print(a/b)

0.5


In [27]:
print(a%b)

10


In [28]:
print((a*b)+(a/b))

200.5


In [29]:
#Various ways of printing

In [30]:
print("Hello")

Hello


In [31]:
first_name='Rohith'
last_name='Neelagiriyappa'

In [33]:
print("My first name is {} and my last name is {}".format(first_name,last_name))

My first name is Rohith and my last name is Neelagiriyappa


In [34]:
print("My First name is {first} and last name is {last}".format(last=last_name,first=first_name))

My First name is Rohith and last name is Neelagiriyappa


In [35]:
len(last_name)

14

In [36]:
len(first_name)

6

In [37]:
type([1,'200','UK'])

list

## Python Data Structures and Boolean 

- Boolean
- Boolean and Logical Operators
- Lists
- Comparison operators
- Dictionaries
- Tuples
- Sets

### Boolean Variables

Boolean values are the two constant objects False and True. 

They are used to represent truth values (other values can also be considered
false or true). 

In numeric contexts (for example, when used as the argument to an
arithmetic operator), they behave like the integers 0 and 1, respectively.

The built-in function bool() can be used to cast any value to a Boolean,
if the value can be interpreted as a truth value

They are written as False and True, respectively.


In [39]:
False

False

In [40]:
print(True,False)

True False


In [41]:
type(True)

bool

In [42]:
type(False)

bool

In [43]:
my_str='Rohith'

In [44]:
my_str.istitle()

True

In [46]:
print(my_str.isalnum()) #check if all char are numbers
print(my_str.isalpha()) #check if all char in the string are alphabetic
print(my_str.isdigit()) #test if string contains digits
print(my_str.istitle()) #test if string contains title words
print(my_str.isupper()) #test if string contains upper case
print(my_str.islower()) #test if string contains lower case
print(my_str.isspace()) #test if string contains spaces
print(my_str.endswith('r')) #test if string endswith a d
print(my_str.startswith('R')) #test if string startswith H

True
True
False
True
False
False
False
False
True


In [47]:
## Boolean and Logical Operators

In [49]:
True and True

True

In [50]:
True and False

False

In [51]:
True or False

True

In [52]:
True or True

True

In [57]:
a='Hello_world'

In [58]:
b='Rohith'

In [60]:
b.isalpha() or a.isnum()

True

### Lists

A list is a data structure in Python that is a mutable, or changeable, ordered sequence of elements. Each element or value that is inside of a list is called an item. Just as strings are defined as characters between quotes, lists are defined by having values between square brackets [ ] 

In [61]:
type([])

list

In [62]:
last_example=[]

In [63]:
type(last_example)

list

In [65]:
lst=list()

In [66]:
type(lst)

list

In [67]:
lst=['Mathematics','Biology',1,2,3,4,5]

In [68]:
len(lst)

7

In [69]:
type(lst)

list

In [71]:
## Append - it is used to add elements in the list

In [72]:
lst

['Mathematics', 'Biology', 1, 2, 3, 4, 5]

In [73]:
lst.append('Canada')

In [74]:
lst

['Mathematics', 'Biology', 1, 2, 3, 4, 5, 'Canada']

In [75]:
lst.append(['Bella','John'])

In [76]:
lst

['Mathematics', 'Biology', 1, 2, 3, 4, 5, 'Canada', ['Bella', 'John']]

In [77]:
#Indexing in list


In [78]:
lst[6]

5

In [79]:
lst[1:6]

['Biology', 1, 2, 3, 4]

In [80]:
## Insert - In a specific order

In [81]:
lst.insert(1,'Karnataka')

In [82]:
lst

['Mathematics',
 'Karnataka',
 'Biology',
 1,
 2,
 3,
 4,
 5,
 'Canada',
 ['Bella', 'John']]

In [84]:
lst.append(['Hello','world'])

In [85]:
lst

['Mathematics',
 'Karnataka',
 'Biology',
 1,
 2,
 3,
 4,
 5,
 'Canada',
 ['Bella', 'John'],
 ['Hello', 'world']]

In [86]:
lst=[1,2,3]

In [87]:
lst.append([4,5])

In [88]:
lst

[1, 2, 3, [4, 5]]

In [89]:
## Extend method

In [90]:
lst=[1,2,3,4,5,6]

In [92]:
lst.extend([7,8])

In [93]:
lst

[1, 2, 3, 4, 5, 6, 7, 8]

In [95]:
### Various Operations that we can perform in List

In [96]:
lst=[1,2,3]

In [97]:
sum(lst)

6

In [98]:
lst*5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [99]:
## pop() method

In [100]:
lst

[1, 2, 3]

In [101]:
lst.pop()

3

In [102]:
lst

[1, 2]

In [103]:
lst=[1,2,3,4,5]

In [104]:
lst.pop(3)

4

In [105]:
lst

[1, 2, 3, 5]

In [106]:
### count():Calculates total occurrence of given element of List

In [107]:
lst=[1,1,1,2,2,3,4,5,5,6,78]

In [108]:
lst.count(2)

2

In [109]:
len(lst)

11

In [110]:
min(lst)

1

In [111]:
max(lst)

78

In [116]:
lst

[1, 1, 1, 2, 2, 3, 4, 5, 5, 6, 78]

## SETS

A Set is an unordered collection data type that is iterable, mutable, and has no duplicate elements. Python's set class represents the mathematical notion of a set.This is based on a data structure known as a hash table

In [127]:
a=set()
print(a)

set()


In [129]:
print(type(a))

<class 'set'>


In [130]:
set_var={1,2,3,4,5}

In [131]:
type(set_var)

set

In [132]:
set_var={"Avengers","IronMan",'Hitman'}
print(set_var)
type(set_var)

{'Hitman', 'Avengers', 'IronMan'}


set

In [133]:
## Inbuilt function in sets

set_var.add("Hulk")

In [134]:
set_var

{'Avengers', 'Hitman', 'Hulk', 'IronMan'}

In [147]:
set1={"Avengers","IronMan",'Hitman'}
set2={"Avengers","IronMan",'Hitman','Hulk2'}

In [144]:
set2.intersection_update(set1)

In [145]:
set2

{'Avengers', 'Hitman', 'IronMan'}

In [148]:
set2.difference(set1)

{'Hulk2'}

In [150]:
print(set2)

{'Hitman', 'Avengers', 'IronMan', 'Hulk2'}


In [152]:
set={11,1,1,1,111,1,111,111,11,1,1,1,11}

In [153]:
set

{1, 11, 111}

## Dictionaries

A dictionary is a collection which is unordered, changeable and indexed. In Python dictionaries are written with curly brackets, and they have keys and values.

In [154]:
dic={}

In [155]:
type(dic)

dict

In [156]:
x={1,2,3,4,5}

In [157]:
type(x)

set

In [158]:
my_dic={"Car1":'Audi',"Car2":'BMW'}

In [159]:
my_dic

{'Car1': 'Audi', 'Car2': 'BMW'}

In [160]:
my_dic['Car1']

'Audi'

In [162]:
for x in my_dic:
    print(x)

Car1
Car2


In [163]:
for x in my_dic.values():  # Printing values 
    print(x)

Audi
BMW


In [165]:
for x in my_dic.keys():  # Printing keys 
    print(x)

Car1
Car2


In [166]:
for x in my_dic.items():  # Printing items 
    print(x)

('Car1', 'Audi')
('Car2', 'BMW')


In [167]:
## Adding items in Dictionaries
my_dic["Car3"]='Mercedes'

In [168]:
my_dic

{'Car1': 'Audi', 'Car2': 'BMW', 'Car3': 'Mercedes'}

In [169]:
a={'Audi':1970}
b={'BMW':1980}
c={'Ambasador':1990}


In [170]:
car_type={'car1':a,'car2':b,'car3':c}

In [171]:
car_type

{'car1': {'Audi': 1970}, 'car2': {'BMW': 1980}, 'car3': {'Ambasador': 1990}}

In [174]:
print(car_type['car1'])

{'Audi': 1970}


In [177]:
print(car_type['car1']['Audi'])

1970


In [178]:
## Tuples

In [180]:
my_typ=tuple()

In [181]:
my_typ

()

In [182]:
type(my_typ)

tuple

In [184]:
my_typ=("Rohith","Bangalore","India")

In [185]:
my_typ

('Rohith', 'Bangalore', 'India')

In [186]:
print(my_typ)

('Rohith', 'Bangalore', 'India')


In [187]:
print(type(my_typ))

<class 'tuple'>


In [188]:
my_typ.count('Rohith')

1

In [189]:
my_typ.count('1')

0

## Numpy ##

## Numpy Tutorials

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

### What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
import numpy as np

In [2]:
a=[1,2,3,4,5]

In [4]:
my_array=np.array(a)

In [5]:
my_array

array([1, 2, 3, 4, 5])

In [6]:
print(my_array)

[1 2 3 4 5]


In [7]:
type(my_array)

numpy.ndarray

In [10]:
x=[1,2,3,4,5]
y=[6,7,8,9,10]
z=[11,12,13,14,15]

In [11]:
new_arr=np.array([x,y,z])

In [12]:
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
print(new_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [14]:
type(new_arr)

numpy.ndarray

In [15]:
new_arr.shape

(3, 5)

In [16]:
## Indexing : Accessing the array elements

In [17]:
x=np.array([1,2,3,4,5])

In [18]:
x

array([1, 2, 3, 4, 5])

In [19]:
x[3]

4

In [20]:
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [21]:
new_arr[:,:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [22]:
new_arr[1:,:2]

array([[ 6,  7],
       [11, 12]])

In [23]:
x

array([1, 2, 3, 4, 5])

In [24]:
x[3:]

array([4, 5])

In [26]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
c=np.arange(0,5)
d=np.arange(0,5)

In [34]:
c

array([0, 1, 2, 3, 4])

In [35]:
d

array([0, 1, 2, 3, 4])

In [36]:
c*d

array([ 0,  1,  4,  9, 16])

In [37]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [39]:
## random distribution
n=np.random.rand(3,3)

In [40]:
n

array([[0.85755615, 0.66914869, 0.5754305 ],
       [0.61617752, 0.7401858 , 0.36382579],
       [0.90945631, 0.61466803, 0.28581864]])

In [41]:
k=np.random.rand(4,4)

In [42]:
k

array([[0.25424205, 0.78062002, 0.50772927, 0.86674399],
       [0.68623374, 0.08386815, 0.3484707 , 0.324877  ],
       [0.59016941, 0.11937954, 0.32189191, 0.01008308],
       [0.64856832, 0.00568689, 0.87409641, 0.73888646]])

In [46]:
np.random.randint(0,100,8).reshape(4,2)

array([[ 6, 91],
       [55, 10],
       [30,  7],
       [66, 43]])

In [1]:
## Pandas

####   pandas is a software library written for the Python programming language for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Data frame

In [3]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['column1','column2','column3','column4'])

In [4]:
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [14]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [15]:
df.loc['row1']

column1    0
column2    1
column3    2
column4    3
Name: row1, dtype: int32

In [16]:
df.loc['row4']

column1    12
column2    13
column3    14
column4    15
Name: row4, dtype: int32

In [5]:
df.iloc[:,:]

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [19]:
df.iloc[:,1:] # Taking the elements from column2

column2  column3  column4
row1        1        2        3
row2        5        6        7
row3        9       10       11
row4       13       14       15
row5       17       18       19

In [7]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [8]:
df['column1']

row1     0
row2     4
row3     8
row4    12
row5    16
Name: column1, dtype: int32

In [11]:
df['column1'].value_counts()

12    1
4     1
16    1
8     1
0     1
Name: column1, dtype: int64

In [12]:
df=pd.read_csv("mercedesbenz.csv")

In [13]:
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [15]:
df.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [16]:
df['X10'].value_counts()

0    4153
1      56
Name: X10, dtype: int64

In [17]:
df['X0'].value_counts() # Helps to get the ubnique values in the category

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
i      18
am     18
aq     18
u      17
aw     16
l      16
ad     14
b      11
k      11
au     11
as     10
r      10
bc      6
ao      4
c       3
aa      2
q       2
ab      1
g       1
ac      1
Name: X0, dtype: int64

In [18]:
df['y']

0       130.81
1        88.53
2        76.26
3        80.62
4        78.02
         ...  
4204    107.39
4205    108.77
4206    109.22
4207     87.48
4208    110.85
Name: y, Length: 4209, dtype: float64

In [19]:
df['y']>100

0        True
1       False
2       False
3       False
4       False
        ...  
4204     True
4205     True
4206     True
4207    False
4208     True
Name: y, Length: 4209, dtype: bool

In [20]:
df[df['y']>100]

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
6       24  128.76  al  r   e  f  d   f  h  s  ...     0     0     0     0   
8       27  108.67   w  s  as  e  d   f  i  h  ...     1     0     0     0   
9       30  126.99   j  b  aq  c  d   f  a  e  ...     0     0     1     0   
10      31  102.09   h  r   r  f  d   f  h  p  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4202  8402  123.34  ap  l   s  c  d  aa  d  r  ...     0     0     0     0   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
6        0     0     0     0     0     0  
8        0     0     0     0     0     0  
9        0     0     0     0     0     0  
10       0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4202     0     0     0     0     0     0  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[2004 rows x 378 columns]

In [21]:
df.corr()

ID         y       X10  X11       X12       X13       X14  \
ID    1.000000 -0.055108  0.001602  NaN  0.058988 -0.031917 -0.025438   
y    -0.055108  1.000000 -0.026985  NaN  0.089792  0.048276  0.193643   
X10   0.001602 -0.026985  1.000000  NaN -0.033084 -0.028806 -0.100474   
X11        NaN       NaN       NaN  NaN       NaN       NaN       NaN   
X12   0.058988  0.089792 -0.033084  NaN  1.000000  0.214825 -0.246513   
...        ...       ...       ...  ...       ...       ...       ...   
X380 -0.013577  0.040932 -0.010479  NaN -0.005566  0.023045  0.007743   
X382 -0.038171 -0.159815 -0.010164  NaN -0.024937 -0.021713  0.012713   
X383 -0.009332  0.040291 -0.004740  NaN -0.011628 -0.010125  0.023604   
X384 -0.015355 -0.004591 -0.002532  NaN -0.006212  0.041242  0.025199   
X385  0.029059 -0.022280 -0.004387  NaN -0.010765 -0.009373  0.043667   

           X15       X16       X17  ...      X375      X376      X377  \
ID    0.002237 -0.036480 -0.038171  ...  0.045229 -0.080259 -0.022965   
y     0.023116  0.048946 -0.159815  ...  0.029100  0.114005  0.061403   
X10  -0.002532 -0.005944 -0.010164  ...  0.165277 -0.028618 -0.074244   
X11        NaN       NaN       NaN  ...       NaN       NaN       NaN   
X12  -0.006212 -0.014584 -0.024937  ... -0.107864 -0.070214  0.030134   
...        ...       ...       ...  ...       ...       ...       ...   
X380 -0.001968 -0.004619 -0.007899  ... -0.061741 -0.022240 -0.061168   
X382 -0.001908 -0.004480  1.000000  ... -0.059883 -0.021571 -0.059327   
X383 -0.000890 -0.002089 -0.003572  ... -0.015413 -0.010059  0.035107   
X384 -0.000475 -0.001116 -0.001908  ... -0.014917 -0.005373  0.008694   
X385 -0.000824 -0.001934 -0.003307  ...  0.055225 -0.009311 -0.025610   

          X378      X379      X380      X382      X383      X384      X385  
ID    0.030371  0.023382 -0.013577 -0.038171 -0.009332 -0.015355  0.029059  
y    -0.258679  0.067919  0.040932 -0.159815  0.040291 -0.004591 -0.022280  
X10  -0.016870 -0.011374 -0.010479 -0.010164 -0.004740 -0.002532 -0.004387  
X11        NaN       NaN       NaN       NaN       NaN       NaN       NaN  
X12  -0.016043 -0.027907 -0.005566 -0.024937 -0.011628 -0.006212 -0.010765  
...        ...       ...       ...       ...       ...       ...       ...  
X380 -0.013110 -0.008839  1.000000 -0.007899 -0.003683 -0.001968 -0.003410  
X382 -0.012716 -0.008573 -0.007899  1.000000 -0.003572 -0.001908 -0.003307  
X383 -0.005930 -0.003998 -0.003683 -0.003572  1.000000 -0.000890 -0.001542  
X384 -0.003168 -0.002136 -0.001968 -0.001908 -0.000890  1.000000 -0.000824  
X385 -0.005489 -0.003701 -0.003410 -0.003307 -0.001542 -0.000824  1.000000  

[370 rows x 370 columns]

In [22]:
df['X11'].value_counts()

0    4209
Name: X11, dtype: int64

In [26]:
import pandas as pd
import numpy as np

In [27]:
last_data=[[1,2,3],[4,5,np.nan],[6,7,np.nan],[np.nan,np.nan,np.nan]]

In [28]:
df=pd.DataFrame(last_data)

In [29]:
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  NaN
2  6.0  7.0  NaN
3  NaN  NaN  NaN

In [30]:
df.head()

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  NaN
2  6.0  7.0  NaN
3  NaN  NaN  NaN

In [9]:
import numpy as np
import pandas as pd
data=pd.DataFrame(np.random.randn(5,3),index=['a','c','e','f','h'],columns=['one','two','three'])

In [10]:
data

one       two     three
a  0.982852 -0.614507  0.374591
c  0.160108  0.955905  0.083390
e  1.401141  0.893132  1.556242
f  1.355158 -1.350942 -0.052859
h -0.217041  2.318889  0.313340

In [11]:
data.head()

one       two     three
a  0.982852 -0.614507  0.374591
c  0.160108  0.955905  0.083390
e  1.401141  0.893132  1.556242
f  1.355158 -1.350942 -0.052859
h -0.217041  2.318889  0.313340

In [12]:
df2=data.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])

In [13]:
df2

one       two     three
a  0.982852 -0.614507  0.374591
b       NaN       NaN       NaN
c  0.160108  0.955905  0.083390
d       NaN       NaN       NaN
e  1.401141  0.893132  1.556242
f  1.355158 -1.350942 -0.052859
g       NaN       NaN       NaN
h -0.217041  2.318889  0.313340

In [14]:
df2.dropna(axis=0)

one       two     three
a  0.982852 -0.614507  0.374591
c  0.160108  0.955905  0.083390
e  1.401141  0.893132  1.556242
f  1.355158 -1.350942 -0.052859
h -0.217041  2.318889  0.313340

In [15]:
df2

one       two     three
a  0.982852 -0.614507  0.374591
b       NaN       NaN       NaN
c  0.160108  0.955905  0.083390
d       NaN       NaN       NaN
e  1.401141  0.893132  1.556242
f  1.355158 -1.350942 -0.052859
g       NaN       NaN       NaN
h -0.217041  2.318889  0.313340

In [17]:
pd.isna(df2['one'])

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool

In [18]:
df2['one'].isna()

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool

In [20]:
df2['one'].notna()

a     True
b    False
c     True
d    False
e     True
f     True
g    False
h     True
Name: one, dtype: bool

In [21]:
import pandas as pd

In [22]:
df=pd.read_csv("Salaries.csv")

In [23]:
df

rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [25]:
df.groupby(['discipline']).sum()

phd  service   salary
discipline                       
A           775      566  3539920
B           762      608  4885935

In [26]:
df.groupby(['discipline']).mean()

phd    service         salary
discipline                                     
A           21.527778  15.722222   98331.111111
B           18.142857  14.476190  116331.785714